import fs from 'node:fs';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { mod, tempHome, write } from './helpers';

// Never depend on whether MO2 or the game happens to be open on this PC.
vi.mock('../electron/loadOrderWrite', async (importOriginal) => ({
  ...(await importOriginal<typeof import('../electron/loadOrderWrite')>()),
  isRunning: () => false,
}));

const { planPluginOrder, pluginLoadOrder, readPluginHeader, setPluginModsEnabled, setPluginOrder } = await import('../electron/bethesdaPlugins');

let env: ReturnType<typeof tempHome>;
beforeEach(() => {
  env = tempHome();
});
afterEach(() => env.restore());

/** A minimal plugin file: TES4 header with flags and MAST records. */
function plugin(file: string, masters: string[] = [], flags = 0): string {
  const subs = masters.map((m) => {
    const data = Buffer.from(`${m}\0`, 'latin1');
    const head = Buffer.alloc(6);
    head.write('MAST', 0, 'latin1');
    head.writeUInt16LE(data.length, 4);
    return Buffer.concat([head, data]);
  });
  const body = Buffer.concat(subs);
  const head = Buffer.alloc(24);
  head.write('TES4', 0, 'latin1');
  head.writeUInt32LE(body.length, 4);
  head.writeUInt32LE(flags, 8);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, Buffer.concat([head, body]));
  return file;
}

/** Fake MO2 instance (global, under LOCALAPPDATA) for Skyrim with profile "P". */
function setup(plugins: string, modlist: string) {
  const root = path.join(process.env.LOCALAPPDATA!, 'ModOrganizer', 'Skyrim');
  const game = path.join(env.home, 'Game');
  write(
    path.join(root, 'ModOrganizer.ini'),
    `[General]\ngameName=Skyrim Special Edition\ngamePath=@ByteArray(${game.replace(/\\/g, '\\\\')})\nselected_profile=@ByteArray(P)\n`,
  );
  const prof = path.join(root, 'profiles', 'P');
  write(path.join(prof, 'plugins.txt'), `# This file was automatically generated by Mod Organizer.\n${plugins}\n`);
  write(path.join(prof, 'loadorder.txt'), '# This file was automatically generated by Mod Organizer.\nSkyrim.esm\n');
  write(path.join(prof, 'modlist.txt'), `# This file was automatically generated by Mod Organizer.\n${modlist}\n`);
  return { root, prof, data: path.join(game, 'Data') };
}

describe('plugin headers', () => {
  it('reads master/light flags and required masters', () => {
    const f = plugin(path.join(env.home, 'X.esp'), ['Skyrim.esm', 'B.esm'], 0x200);
    expect(readPluginHeader(f)).toEqual({ master: false, light: true, masters: ['Skyrim.esm', 'B.esm'] });
    expect(readPluginHeader(write(path.join(env.home, 'junk.esp'), 'not a plugin'))).toBeNull();
  });
});

describe('Skyrim plugin order (MO2 profile)', () => {
  it('sorts masters first and flags a plugin loading before its master', () => {
    const { root, data } = setup('*A.esp\n*B.esm', '+ModA');
    plugin(path.join(root, 'mods', 'ModA', 'A.esp'), ['Skyrim.esm', 'B.esm']);
    plugin(path.join(data, 'B.esm'), ['Skyrim.esm'], 0x1);
    const plan = planPluginOrder('skyrimse', [])!;
    expect(plan.current).toEqual(['A.esp', 'B.esm']);
    expect(plan.proposed).toEqual(['B.esm', 'A.esp']);
    expect(plan.issues.map((i) => i.kind)).toEqual(['order']);
  });

  it('flags missing and switched-off masters', () => {
    const { data } = setup('*A.esp\nB.esm', '');
    plugin(path.join(data, 'A.esp'), ['B.esm', 'Gone.esm']);
    plugin(path.join(data, 'B.esm'), [], 0x1);
    const kinds = planPluginOrder('skyrimse', [])!.issues.map((i) => `${i.kind}:${i.otherId}`);
    expect(kinds).toContain('dependency-off:B.esm');
    expect(kinds).toContain('dependency-missing:Gone.esm');
  });

  it('flags an SKSE DLL whose plugin is off, and enabling the mod switches the plugin on', () => {
    const { prof, data } = setup('*Other.esp', '');
    plugin(path.join(data, 'Other.esp'));
    const staging = path.join(env.home, 'Vortex', 'OStim');
    plugin(path.join(staging, 'OStim.esp'), ['Skyrim.esm']);
    write(path.join(staging, 'SKSE', 'Plugins', 'OStim.dll'), 'x');
    plugin(path.join(data, 'OStim.esp'), ['Skyrim.esm']);
    const ostim = mod({ id: 'ostim', gameId: 'skyrimse', source: 'vortex-staging', title: 'OStim', localPath: staging });

    expect(planPluginOrder('skyrimse', [ostim])!.issues.some((i) => i.otherId === 'ostim')).toBe(true);
    expect(pluginLoadOrder('skyrimse', [ostim])!.mods.ostim.enabled).toBe(false);

    const r = setPluginModsEnabled('skyrimse', [ostim], true);
    expect(r.ok).toBe(true);
    expect(fs.readFileSync(path.join(prof, 'plugins.txt'), 'utf8')).toContain('*OStim.esp');
    const after = pluginLoadOrder('skyrimse', [ostim])!.mods.ostim;
    expect(after.enabled).toBe(true);
    // 5 base-game masters load first, then Other.esp, then OStim.esp.
    expect(after.position).toBe(7);
    expect(planPluginOrder('skyrimse', [ostim])!.issues).toEqual([]);
  });

  it('switches an MO2 mod off in modlist.txt and saves a new plugin order', () => {
    const { root, prof } = setup('*A.esp\n*C.esp', '+ModA\n+ModC');
    plugin(path.join(root, 'mods', 'ModA', 'A.esp'));
    plugin(path.join(root, 'mods', 'ModC', 'C.esp'));
    const modA = mod({ id: 'a', gameId: 'skyrimse', source: 'local', localPath: path.join(root, 'mods', 'ModA'), mo2: { instance: root, name: 'ModA' } });

    expect(setPluginModsEnabled('skyrimse', [modA], false).ok).toBe(true);
    expect(fs.readFileSync(path.join(prof, 'modlist.txt'), 'utf8')).toContain('-ModA');
    expect(fs.readFileSync(path.join(prof, 'plugins.txt'), 'utf8')).toMatch(/^A\.esp$/m);

    expect(setPluginOrder('skyrimse', ['C.esp', 'A.esp']).ok).toBe(true);
    expect(fs.readFileSync(path.join(prof, 'plugins.txt'), 'utf8').split(/\r?\n/).slice(1, 3)).toEqual(['*C.esp', 'A.esp']);
    expect(fs.readFileSync(path.join(prof, 'loadorder.txt'), 'utf8')).toMatch(/Dragonborn\.esm\r?\nC\.esp\r?\nA\.esp/);
    expect(setPluginOrder('skyrimse', ['C.esp']).ok).toBe(false);
  });
});

describe('script extender checks', () => {
  it('flags a Skyrim VR SKSE build installed on Skyrim SE', () => {
    setup('', '');
    const vr = mod({ id: 'vr', gameId: 'skyrimse', source: 'nexus', title: 'Skyrim Script Extender for VR (SKSEVR)', localPath: env.home });
    expect(planPluginOrder('skyrimse', [vr])!.issues.map((i) => `${i.kind}:${i.otherId}`)).toEqual(['incompatible:vr']);
  });
});

describe('Vortex / MO2 plugin sync', () => {
  it('lists differences and copies on/off in either direction', async () => {
    const { pluginSync } = await import('../electron/bethesdaPlugins');
    const { prof } = setup('*A.esp\nB.esp\n*OnlyMo2.esp', '');
    const vortexFile = write(
      path.join(process.env.LOCALAPPDATA!, 'Skyrim Special Edition', 'plugins.txt'),
      '# Automatically generated by Vortex\nA.esp\n*B.esp\n',
    );
    const preview = pluginSync('skyrimse', 'vortex-to-mo2');
    expect(preview.differences.map((d) => d.name)).toEqual(['A.esp', 'B.esp']);
    expect(fs.readFileSync(path.join(prof, 'plugins.txt'), 'utf8')).toContain('*A.esp'); // preview changes nothing

    expect(pluginSync('skyrimse', 'vortex-to-mo2', undefined, true).ok).toBe(true);
    const mo2 = fs.readFileSync(path.join(prof, 'plugins.txt'), 'utf8');
    expect(mo2).toMatch(/^A\.esp$/m);
    expect(mo2).toMatch(/^\*B\.esp$/m);
    expect(mo2).toMatch(/^\*OnlyMo2\.esp$/m); // not in Vortex: left alone

    fs.writeFileSync(vortexFile, '# Automatically generated by Vortex\n*A.esp\nB.esp\n');
    expect(pluginSync('skyrimse', 'mo2-to-vortex', undefined, true).ok).toBe(true);
    expect(fs.readFileSync(vortexFile, 'utf8').split(/\r?\n/).slice(1, 3)).toEqual(['A.esp', '*B.esp']);
  });
});
