import fs from 'node:fs';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { mod, tempHome, write } from './helpers';

vi.mock('../electron/loadOrderWrite', async (importOriginal) => ({
  ...(await importOriginal<typeof import('../electron/loadOrderWrite')>()),
  isRunning: () => false,
}));

const { cleanModName, migrateVortexToMo2, planVortexToMo2 } = await import('../electron/mo2Migrate');

let env: ReturnType<typeof tempHome>;
beforeEach(() => {
  env = tempHome();
});
afterEach(() => env.restore());

function setup() {
  const root = path.join(process.env.LOCALAPPDATA!, 'ModOrganizer', 'Skyrim');
  write(path.join(root, 'ModOrganizer.ini'), '[General]\ngameName=Skyrim Special Edition\nselected_profile=@ByteArray(Main)\n');
  write(path.join(root, 'profiles', 'Main', 'modlist.txt'), '# This file was automatically generated by Mod Organizer.\n+SkyUI\n');
  write(path.join(root, 'profiles', 'Other', 'modlist.txt'), '# This file was automatically generated by Mod Organizer.\n+SkyUI\n');
  fs.mkdirSync(path.join(root, 'mods', 'SkyUI'), { recursive: true });
  const staging = path.join(env.home, 'Vortex Mods', 'skyrimse');
  write(path.join(staging, 'CBPC 21224 1.7.2 2026-08-30T23-48Z kATsMWw0A', 'SKSE', 'Plugins', 'cbp.dll'), 'x');
  write(path.join(staging, 'Preloader-17230-7-1771936758', 'd3dx9_42.dll'), 'x');
  write(path.join(staging, 'Old Disabled-1-1-1700000000', 'old.esp'), 'x');
  write(path.join(staging, 'vortex.deployment.json'), JSON.stringify({ files: [{ relPath: 'SKSE/Plugins/cbp.dll', source: 'CBPC 21224 1.7.2 2026-08-30T23-48Z kATsMWw0A' }] }));
  write(path.join(staging, 'vortex.deployment.dinput.json'), JSON.stringify({ files: [{ relPath: 'd3dx9_42.dll', source: 'Preloader-17230-7-1771936758' }] }));
  const mods = [
    mod({ id: 'cbpc', gameId: 'skyrimse', source: 'nexus', title: 'CBPC 21224 1.7.2 2026-08-30T23-48Z kATsMWw0A', localPath: path.join(staging, 'CBPC 21224 1.7.2 2026-08-30T23-48Z kATsMWw0A'), nexusModId: 21224, version: '1.7.2' }),
  ];
  return { root, mods };
}

describe('Vortex → MO2', () => {
  it('cleans Vortex folder names', () => {
    expect(cleanModName('CBPC - Fomod installer - MAIN FILE 21224 1.7.2 2026-08-30T23-48Z kATsMWw0A')).toBe('CBPC - Fomod installer - MAIN FILE');
    expect(cleanModName('Nemesis Unlimited Behavior Engine-60033-v0-84-beta-1639426722')).toBe('Nemesis Unlimited Behavior Engine');
  });

  it('plans only deployed mods and flags game-root ones', () => {
    const { mods } = setup();
    const plan = planVortexToMo2('skyrimse', mods);
    expect(plan.items.map((i) => `${i.status}:${i.title}`)).toEqual(['copy:CBPC', 'root-files:Preloader']);
  });

  it('copies with meta.ini and adds to every profile (on in the chosen one)', () => {
    const { root, mods } = setup();
    const r = migrateVortexToMo2('skyrimse', mods, 'Main');
    expect(r.ok).toBe(true);
    expect(fs.existsSync(path.join(root, 'mods', 'CBPC', 'SKSE', 'Plugins', 'cbp.dll'))).toBe(true);
    expect(fs.readFileSync(path.join(root, 'mods', 'CBPC', 'meta.ini'), 'utf8')).toMatch(/modid=21224\r\nversion=1\.7\.2/);
    expect(fs.readFileSync(path.join(root, 'profiles', 'Main', 'modlist.txt'), 'utf8').split(/\r?\n/).slice(1, 3)).toEqual(['+CBPC', '+SkyUI']);
    expect(fs.readFileSync(path.join(root, 'profiles', 'Other', 'modlist.txt'), 'utf8')).toMatch(/^-CBPC$/m);
    // Running again copies nothing (already there).
    expect(planVortexToMo2('skyrimse', mods).items[0].status).toBe('exists');
  });
});
